In [2]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import SVC

/home/enes/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [3]:
data = pd.read_csv('train_data_last.csv')
data.head()

attr0      attr1     attr10     attr11     attr12     attr13  \
0 -28.078741 -33.102219 -11.285934 -55.467064 -18.698963  20.853622   
1 -27.188370 -33.396988 -11.918320 -54.489632 -19.096252  21.023575   
2 -28.299839 -31.300903 -14.482681 -53.193886 -18.344807  21.273041   
3 -28.520922 -30.162552  -8.071472 -54.272041 -18.439487  19.767334   
4 -28.918324 -30.329834 -10.956329 -54.959209 -18.164555  20.332703   

      attr14     attr15     attr16     attr17  ...       attr55     attr56  \
0 -17.109612 -23.905125  -9.947266 -41.739864  ...   -31.147964 -19.388859   
1 -16.450127 -25.071028  -9.944946 -40.692688  ...   -31.098404 -19.529282   
2 -16.976151 -25.308964  -9.313583 -41.438503  ...   -31.828354 -19.951521   
3 -18.614567 -24.219011 -13.630142 -39.438927  ...   -35.717682 -16.122189   
4 -18.272774 -24.213734 -11.925491 -40.750877  ...   -32.437271 -17.347183   

      attr57     attr58    attr59      attr6      attr7      attr8      attr9  \
0   3.427349 -32.970428 -4.637733 -34.235989 -10.999771 -36.119789 -24.479454   
1   3.211506 -32.988907 -4.611134 -35.601997 -11.083893 -35.368584 -25.439411   
2   1.842770 -33.410706 -5.161762 -33.762383 -11.485458 -35.284233 -21.936567   
3  10.490032 -38.959778 -0.587688 -35.226231  -8.306229 -34.155270 -27.173328   
4   2.929779 -32.878448 -2.351490 -35.931263 -10.332428 -35.078346 -27.331793   

   label  
0      A  
1      A  
2      A  
3      A  
4      A  

[5 rows x 61 columns]

In [4]:
 X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,:-1], data.label, test_size=0.2, random_state=42)

In [5]:
clf = RandomForestClassifier(n_estimators=15, max_depth=3, random_state=0)
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=15, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [6]:
y_preds = clf.predict(X_train)

In [7]:
confusion_matrix(y_train,y_preds)

array([[165,   0,   3],
       [  4, 154,   1],
       [  2,   2, 149]])

In [8]:
accuracy_score(y_preds,y_train)

0.975

In [9]:
y_preds = clf.predict(X_test)

In [10]:
confusion_matrix(y_test,y_preds)

array([[32,  0,  1],
       [ 1, 43,  0],
       [ 1,  1, 41]])

In [11]:
accuracy_score(y_preds,y_test)

0.9666666666666667

In [12]:
svc = SVC()
svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
y_preds = svc.predict(X_train)

In [14]:
confusion_matrix(y_train,y_preds)

array([[168,   0,   0],
       [  0, 159,   0],
       [  0,   0, 153]])

In [15]:
accuracy_score(y_preds,y_train)

1.0

In [16]:
y_preds = clf.predict(X_test)

In [17]:
confusion_matrix(y_test,y_preds)

array([[32,  0,  1],
       [ 1, 43,  0],
       [ 1,  1, 41]])

In [18]:
accuracy_score(y_preds,y_test)

0.9666666666666667